version: '3.8'

services:

  adoteumpet:
    image: amazoncorretto:17-alpine
    container_name: adoteumpet-container
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/adoteumpet
    depends_on:
      - database
  database:
    image: postgres:12-alpine
    container_name: database-adoteumpet
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=h5UzM2kEnp8Q42
      - APP_DB_USER=root
      - APP_DB_PASS=123
      - APP_DB_NAME=adoteumpet
    ports:
      - '5433:5432'
    volumes:
      - ./postgres/db:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data